version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    container_name: mongo
    volumes:
      - ./myapp
    ports:
      - "27018:27017"
  openjdk:
    image: "openjdk:8"